name: project2m
dependencies:
- backports=1.0=py35_0
- click=6.6=py35_0
- decorator=4.0.10=py35_0
- docopt=0.6.2=py35_0
- entrypoints=0.2.2=py35_0
- flake8=2.5.1=py35_0
- flask=0.11.1=py35_0
- fontconfig=2.11.1=6
- freetype=2.5.5=1
- get_terminal_size=1.0.0=py35_0
- ipykernel=4.3.1=py35_0
- ipython=4.2.0=py35_0
- ipython_genutils=0.1.0=py35_0
- ipywidgets=4.1.1=py35_0
- itsdangerous=0.24=py35_0
- jinja2=2.8=py35_1
- jsonschema=2.5.1=py35_0
- jupyter=1.0.0=py35_3
- jupyter_client=4.3.0=py35_0
- jupyter_console=4.1.1=py35_0
- jupyter_core=4.1.0=py35_0
- libpng=1.6.17=0
- libsodium=1.0.10=0
- libxml2=2.9.2=0
- markupsafe=0.23=py35_2
- matplotlib=1.4.3=np110py35_2
- mccabe=0.3.1=py35_0
- mistune=0.7.2=py35_0
- mkl=11.3.3=0
- nbconvert=4.2.0=py35_0
- nbformat=4.0.1=py35_0
- notebook=4.2.1=py35_0
- numpy=1.10.4=py35_2
- openssl=1.0.2h=1
- pandas=0.18.1=np110py35_0
- pandas-datareader=0.2.1=py35_0
- path.py=8.2.1=py35_0
- pep8=1.7.0=py35_0
- pexpect=4.0.1=py35_0
- pickleshare=0.7.2=py35_0
- pip=8.1.2=py35_0
- psycopg2=2.6.1=py35_1
- ptyprocess=0.5.1=py35_0
- pyflakes=1.3.0=py35_0
- pygments=2.1.3=py35_0
- pyparsing=2.0.3=py35_0
- pyqt=4.11.4=py35_3
- python=3.5.2=0
- python-dateutil=2.5.3=py35_0
- pytz=2016.4=py35_0
- pyzmq=15.2.0=py35_1
- qt=4.8.7=3
- qtconsole=4.2.1=py35_0
- readline=6.2=2
- requests=2.10.0=py35_0
- requests-file=1.4=py35_0
- setuptools=23.0.0=py35_0
- simplegeneric=0.8.1=py35_1
- sip=4.16.9=py35_0
- six=1.10.0=py35_0
- sqlalchemy=1.0.13=py35_0
- sqlite=3.13.0=0
- terminado=0.6=py35_0
- tk=8.5.18=0
- tornado=4.3=py35_1
- traitlets=4.2.1=py35_0
- werkzeug=0.11.11=py35_0
- wheel=0.29.0=py35_0
- xlrd=1.0.0=py35_0
- xz=5.2.2=0
- zeromq=4.1.4=0
- zlib=1.2.8=3
- pip:
  - alembic==0.8.6
  - backports.shutil-get-terminal-size==1.0.0
  - easyprocess==0.2.2
  - ipdb==0.10.1
  - ipython-genutils==0.1.0
  - jupyter-client==4.3.0
  - jupyter-console==4.1.1
  - jupyter-core==4.1.0
  - mako==1.0.4
  - python-editor==1.0.1
  - pyvirtualdisplay==0.2
  - requests-cache==0.4.12
  - selenium==2.53.6

