"""table name should be lower case

Revision ID: 4a28225afd61
Revises: 92d1a91f2aef
Create Date: 2016-07-21 00:29:23.713991

"""

# revision identifiers, used by Alembic.
revision = '4a28225afd61'
down_revision = '92d1a91f2aef'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_sentiment',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('asx_code', sa.String(length=255), nullable=False),
    sa.Column('counts', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.drop_table('PreSentiment')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PreSentiment',
    sa.Column('pk', sa.INTEGER(), server_default=sa.text('nextval(\'"PreSentiment_pk_seq"\'::regclass)'), nullable=False),
    sa.Column('asx_code', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('counts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('pk', name='PreSentiment_pkey')
    )
    op.drop_table('pre_sentiment')
    ### end Alembic commands ###
