"""first attempt

Revision ID: 92d1a91f2aef
Revises: 
Create Date: 2016-07-21 00:11:23.189555

"""

# revision identifiers, used by Alembic.
revision = '92d1a91f2aef'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PreSentiment',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('asx_code', sa.String(length=255), nullable=False),
    sa.Column('counts', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PreSentiment')
    ### end Alembic commands ###
